### ISSUE TITLE
Example produces invalid fat-jar.

### ISSUE THREAD

**Issue by MarcinLachowicz** [MarcinLachowicz/spring-boot-javafx-scaffolding#1]
`mvn clean install && java -jar target/spring-boot-javafx-scaffolding-1.0-SNAPSHOT-exec.jar` ends with:
`Caused by: java.lang.StackOverflowError
	at java.util.concurrent.ConcurrentHashMap.putVal(ConcurrentHashMap.java:1012)
	at java.util.concurrent.ConcurrentHashMap.putIfAbsent(ConcurrentHashMap.java:1535)
	at java.lang.ClassLoader.getClassLoadingLock(ClassLoader.java:463)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:404)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:411)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 1017 more`

**Comment by MarcinLachowicz** [comment]
According to [Spring-Boot-2.1-Release-Notes](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.1-Release-Notes#maven-plugin):

> If you were customizing the repackage goal, the main execution has now an id of repackage that must be specified, see the updated sample.

**Comment by MarcinLachowicz** [comment]
Fixed in #2
